apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: project-k8s
  template:
    metadata:
      labels:
        app: project-k8s
    spec:
      containers:
      - name: project-k8s
        image: 139675813056.dkr.ecr.us-east-1.amazonaws.com/jenkins-lab:latest
        ports:
        - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: project-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: project-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 
